version: "3"
services:
  php:
    image: php:8.0-cli-alpine
    working_dir: /opt
    volumes:
      - ./:/opt
    entrypoint: php
    user: ${HOST_UID}:${HOST_GID}
    env_file:
      - .env

  composer:
    image: composer:latest
    volumes:
      - ./:/app
    user: ${HOST_UID}:${HOST_GID}
    env_file:
      - .env
